[package]
name = "snarkvm-console-types-string"
version = "4.10.0"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Type operations for a decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/ProvableHQ/snarkVM"
license = "Apache-2.0"
edition = "2024"

[dependencies.snarkvm-console-network-environment]
workspace = true

[dependencies.snarkvm-console-types-boolean]
workspace = true

[dependencies.snarkvm-console-types-field]
workspace = true

[dependencies.snarkvm-console-types-integers]
workspace = true

[dev-dependencies.bincode]
workspace = true

[dev-dependencies.serde_json]
workspace = true
features = [ "preserve_order" ]
