[package]
name = "snarkvm-console-network-environment"
version = "4.10.0"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Environment console library for a decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/ProvableHQ/snarkVM"
license = "Apache-2.0"
edition = "2024"

[dependencies.snarkvm-curves]
workspace = true

[dependencies.snarkvm-fields]
workspace = true

[dependencies.snarkvm-utilities]
workspace = true

[dependencies.anyhow]
workspace = true

[dependencies.bech32]
version = "0.11"

[dependencies.itertools]
workspace = true

[dependencies.nom]
workspace = true

[dependencies.num-traits]
workspace = true

[dependencies.rand]
workspace = true

[dependencies.serde]
workspace = true

[dependencies.zeroize]
workspace = true
features = [ "derive" ]

[features]
default = [ ]
dev-print = [ "snarkvm-utilities/dev-print" ]
serial = [ "snarkvm-utilities/serial" ]
