[package]
name = "snarkvm-synthesizer-snark"
version = "4.10.0"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "SNARK wrappers for a decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/ProvableHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [
  "compilers",
  "cryptography",
  "mathematics",
  "wasm",
  "web-programming"
]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "Apache-2.0"
edition = "2024"

[features]
default = [ ]
cuda = [ "snarkvm-algorithms/cuda" ]
dev-print = [ "snarkvm-utilities/dev-print" ]
serial = [ "snarkvm-console/serial", "snarkvm-algorithms/serial" ]
wasm = [ "snarkvm-console/wasm" ]
test-helpers = [ ]

[dependencies.snarkvm-circuit]
workspace = true

[dependencies.snarkvm-console]
workspace = true
default-features = false
features = [ "network" ]

[dependencies.snarkvm-algorithms]
workspace = true

[dependencies.snarkvm-utilities]
workspace = true

[dependencies.bincode]
workspace = true

[dependencies.serde_json]
workspace = true
features = [ "preserve_order" ]

[dev-dependencies.snarkvm-console]
workspace = true
default-features = false
features = [ "types" ]
