[package]
name = "snarkvm-circuit-types-string"
version = "4.10.0"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "String circuit for a decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/ProvableHQ/snarkVM"
license = "Apache-2.0"
edition = "2024"

[dependencies.snarkvm-console-types-string]
workspace = true

[dependencies.snarkvm-circuit-environment]
workspace = true

[dependencies.snarkvm-circuit-types-boolean]
workspace = true

[dependencies.snarkvm-circuit-types-field]
workspace = true

[dependencies.snarkvm-circuit-types-integers]
workspace = true

[dev-dependencies.snarkvm-utilities]
workspace = true

[dev-dependencies.rand]
workspace = true
