[package]
name = "snarkvm-synthesizer-program"
version = "4.10.0"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Program for a decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/ProvableHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [
  "compilers",
  "cryptography",
  "mathematics",
  "wasm",
  "web-programming"
]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "Apache-2.0"
edition = "2024"

[features]
default = [ ]
serial = [ "snarkvm-console/serial" ]
wasm = [ "snarkvm-console/wasm" ]

[dependencies.snarkvm-algorithms]
workspace = true

[dependencies.snarkvm-circuit]
workspace = true

[dependencies.snarkvm-console]
workspace = true
features = [ "account", "network", "program", "types" ]

[dependencies.snarkvm-synthesizer-error]
workspace = true

[dependencies.snarkvm-synthesizer-snark]
workspace = true

[dependencies.snarkvm-utilities]
workspace = true

[dependencies.enum-iterator]
workspace = true

[dependencies.indexmap]
workspace = true
features = [ "serde", "rayon" ]

[dependencies.paste]
workspace = true

[dependencies.rand]
workspace = true

[dependencies.rand_chacha]
workspace = true

[dependencies.rayon]
version = "1"

[dependencies.serde_json]
workspace = true
features = [ "preserve_order" ]

[dependencies.tiny-keccak]
version = "2"
features = [ "sha3" ]

[dev-dependencies.bincode]
workspace = true

[dev-dependencies.k256]
workspace = true

[dev-dependencies.snarkvm-console]
workspace = true
features = [ "test" ]

[dev-dependencies.criterion]
workspace = true

[dev-dependencies.snarkvm-synthesizer-process]
path = "../process"
features = [ "test" ]
