[package]
name = "snarkvm-console-account"
version = "4.10.0"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Account operations for a decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/ProvableHQ/snarkVM"
license = "Apache-2.0"
edition = "2024"

[[bench]]
name = "account"
path = "benches/account.rs"
harness = false

[dependencies.snarkvm-console-network]
workspace = true

[dependencies.snarkvm-console-types]
workspace = true
features = [ "address", "boolean", "field", "group", "scalar" ]

[dependencies.bs58]
version = "0.5"

[dependencies.zeroize]
workspace = true
features = [ "derive" ]

[dev-dependencies.bincode]
workspace = true

[dev-dependencies.criterion]
workspace = true

[dev-dependencies.serde_json]
workspace = true
features = [ "preserve_order" ]

[features]
default = [
  "compute_key",
  "graph_key",
  "private_key",
  "signature",
  "view_key"
]
compute_key = [ "private_key" ]
graph_key = [ "private_key" ]
private_key = [ "compute_key" ]
signature = [ "compute_key" ]
view_key = [ ]
test = [ ]
