[package]
name = "snarkvm-synthesizer-process"
version = "4.10.0"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "A process for a decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/ProvableHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [
  "compilers",
  "cryptography",
  "mathematics",
  "wasm",
  "web-programming"
]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "Apache-2.0"
edition = "2024"

[features]
default = [ "indexmap/rayon", "rayon" ]
async = [ "snarkvm-ledger-query/async" ]
locktick = [ "dep:locktick", "snarkvm-ledger-store/locktick" ]
rocks = [ "snarkvm-ledger-store/rocks" ]
serial = [
  "snarkvm-console/serial",
  "snarkvm-ledger-block/serial",
  "snarkvm-ledger-query/serial",
  "snarkvm-ledger-store/serial",
  "snarkvm-synthesizer-program/serial",
  "snarkvm-synthesizer-snark/serial"
]
wasm = [
  "snarkvm-console/wasm",
  "snarkvm-ledger-block/wasm",
  "snarkvm-ledger-query/wasm",
  "snarkvm-synthesizer-program/wasm",
  "snarkvm-synthesizer-snark/wasm"
]
test = [ "snarkvm-console/test", "snarkvm-circuit/test" ]
history = [ "snarkvm-ledger-store/history" ]
timer = [ "aleo-std/timer" ]
dev-print = [ "snarkvm-utilities/dev-print" ]
dev_skip_checks = [ ]
test_consensus_heights = [ ]

[[bench]]
name = "stack_operations"
path = "benches/stack_operations.rs"
harness = false

[[bench]]
name = "check_deployment"
path = "benches/check_deployment.rs"
harness = false

[dependencies.snarkvm-algorithms]
workspace = true

[dependencies.snarkvm-console]
workspace = true
default-features = false
features = [ "network", "program", "types" ]

[dependencies.snarkvm-circuit]
workspace = true

[dependencies.snarkvm-ledger-block]
workspace = true

[dependencies.snarkvm-ledger-query]
workspace = true

[dependencies.snarkvm-ledger-store]
workspace = true

[dependencies.snarkvm-synthesizer-error]
workspace = true

[dependencies.snarkvm-synthesizer-program]
workspace = true

[dependencies.snarkvm-synthesizer-snark]
workspace = true

[dependencies.snarkvm-utilities]
workspace = true

[dependencies.aleo-std]
workspace = true

[dependencies.colored]
workspace = true

[dependencies.indexmap]
workspace = true
features = [ "serde" ]

[dependencies.itertools]
workspace = true

[dependencies.locktick]
workspace = true
features = [ "parking_lot" ]
optional = true

[dependencies.parking_lot]
workspace = true

[dependencies.rand]
workspace = true

[dependencies.rand_chacha]
workspace = true

[dependencies.rayon]
workspace = true
optional = true

[dependencies.serde_json]
workspace = true
features = [ "preserve_order" ]

[dev-dependencies.bincode]
workspace = true

[dev-dependencies.criterion]
workspace = true

[dev-dependencies.snarkvm-ledger-committee]
workspace = true

[dev-dependencies.snarkvm-ledger-query]
workspace = true
features = [ "query" ]

[dev-dependencies.snarkvm-ledger-store]
workspace = true
features = [ "test" ]

[dev-dependencies.snarkvm-circuit]
workspace = true
features = [ "test" ]

[dev-dependencies.snarkvm-ledger-test-helpers]
path = "../../ledger/test-helpers"

[dev-dependencies.tempfile]
workspace = true
