[package]
name = "snarkvm-ledger-narwhal-transmission-id"
version = "4.10.0"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "A transmission ID for a Narwhal-style memory pool in a decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/ProvableHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [
  "compilers",
  "cryptography",
  "mathematics",
  "wasm",
  "web-programming"
]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "Apache-2.0"
edition = "2024"

[features]
default = [ ]
serial = [ "snarkvm-console/serial" ]
wasm = [ "snarkvm-console/wasm" ]
test-helpers = [ ]

[dependencies.snarkvm-console]
workspace = true

[dependencies.snarkvm-ledger-puzzle]
workspace = true

[dev-dependencies.bincode]
workspace = true

[dev-dependencies.serde_json]
workspace = true
features = [ "preserve_order" ]
