[package]
name = "snarkvm-ledger-query"
version = "4.10.0"
authors = ["The Aleo Team <hello@aleo.org>"]
description = "A query for a decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/ProvableHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge",
]
categories = ["cryptography", "web-programming"]
license = "Apache-2.0"
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
edition = "2024"

[features]
default = ["query"]
async = ["dep:reqwest"]
serial = [
  "snarkvm-console/serial",
  "snarkvm-ledger-store/serial",
  "snarkvm-synthesizer-program/serial",
]
wasm = [
  "snarkvm-console/wasm",
  "snarkvm-ledger-store/wasm",
  "snarkvm-synthesizer-program/wasm",
]
query = [
  "dep:snarkvm-ledger-block",
  "dep:snarkvm-ledger-store",
  "dep:snarkvm-synthesizer-program",
  "dep:ureq",
]

[dependencies.snarkvm-console]
workspace = true

[dependencies.snarkvm-ledger-block]
workspace = true
optional = true

[dependencies.snarkvm-ledger-store]
workspace = true
optional = true

[dependencies.snarkvm-synthesizer-program]
workspace = true
optional = true

[dependencies.anyhow]
workspace = true

[dependencies.async-trait]
version = "0.1"

[dependencies.serde]
workspace = true

[dependencies.serde_json]
workspace = true
features = ["preserve_order"]

[target.'cfg(any(target_os = "android", target_os = "ios"))'.dependencies.reqwest]
version = "0.13"
default-features = false
features = ["json", "native-tls"]
optional = true

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies.reqwest]
version = "0.13"
default-features = false
features = ["json", "rustls"]
optional = true

[target.'cfg(target_arch="wasm32")'.dependencies.ureq]
workspace = true
features = ["json", "gzip"]
optional = true

[target.'cfg(not(target_arch="wasm32"))'.dependencies.ureq]
workspace = true
features = ["json", "gzip", "rustls"]
optional = true
