[package]
name = "snarkvm-ledger-puzzle-epoch"
version = "4.10.0"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Epoch puzzle for a decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/ProvableHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [
  "compilers",
  "cryptography",
  "mathematics",
  "wasm",
  "web-programming"
]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "Apache-2.0"
edition = "2024"

[features]
default = [ "synthesis", "rayon" ]
serial = [ "snarkvm-console/serial", "snarkvm-ledger-puzzle/serial" ]
locktick = [
  "dep:locktick",
  "snarkvm-ledger-puzzle/locktick",
  "snarkvm-synthesizer-process/locktick"
]
merkle = [ ]
synthesis = [
  "aleo-std",
  "snarkvm-circuit",
  "lru",
  "parking_lot",
  "snarkvm-synthesizer-process",
  "snarkvm-synthesizer-program"
]
timer = [ "aleo-std/timer" ]
wasm = [ "snarkvm-console/wasm" ]
dev-print = [ "snarkvm-utilities/dev-print" ]

[dependencies.snarkvm-circuit]
workspace = true
optional = true

[dependencies.snarkvm-console]
workspace = true

[dependencies.snarkvm-ledger-puzzle]
workspace = true

[dependencies.snarkvm-synthesizer-process]
workspace = true
optional = true

[dependencies.snarkvm-synthesizer-program]
workspace = true
optional = true

[dependencies.snarkvm-utilities]
workspace = true

[dependencies.aleo-std]
workspace = true
optional = true

[dependencies.anyhow]
workspace = true

[dependencies.colored]
workspace = true

[dependencies.indexmap]
workspace = true
features = [ "serde", "rayon" ]

[dependencies.locktick]
workspace = true
features = [ "parking_lot" ]
optional = true

[dependencies.lru]
workspace = true
optional = true

[dependencies.parking_lot]
workspace = true
optional = true

[dependencies.rand]
workspace = true

[dependencies.rand_chacha]
workspace = true

[dependencies.rayon]
workspace = true
optional = true

[dev-dependencies.snarkvm-console]
workspace = true
features = [ "test" ]

[dev-dependencies.hex]
workspace = true

[dev-dependencies.sha2]
workspace = true
