[package]
name = "snarkvm-parameters"
version = "4.10.0"
authors = ["The Aleo Team <hello@aleo.org>"]
description = "Parameters for a decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/ProvableHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge",
]
categories = [
  "compilers",
  "cryptography",
  "mathematics",
  "wasm",
  "web-programming",
]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "Apache-2.0"
edition = "2024"

[features]
filesystem = ["aleo-std/storage"]
large_params = []
locktick = ["dep:locktick"]
no_std_out = []
rocks = ["snarkvm-ledger-store/rocks"]
no-embedded-srs = []
wasm = ["encoding", "js-sys", "web-sys"]
dev-print = ["snarkvm-utilities/dev-print"]

[dependencies.snarkvm-curves]
workspace = true

[dependencies.snarkvm-utilities]
workspace = true

[dependencies.aleo-std]
workspace = true

[dependencies.anyhow]
workspace = true

[dependencies.cfg-if]
workspace = true

[dependencies.colored]
workspace = true

[dependencies.encoding]
version = "0.2"
optional = true

[dependencies.hex]
workspace = true

[dependencies.js-sys]
version = "0.3.64"
optional = true

[dependencies.lazy_static]
workspace = true

[dependencies.locktick]
workspace = true
features = ["parking_lot"]
optional = true

[dependencies.parking_lot]
workspace = true

[dependencies.paste]
workspace = true

[dependencies.rand]
workspace = true

[dependencies.serde_json]
workspace = true
features = ["preserve_order"]

[dependencies.sha2]
workspace = true

[dependencies.thiserror]
workspace = true

[dependencies.web-sys]
version = "0.3.64"
features = ["XmlHttpRequest"]
optional = true

[target.'cfg(all(any(target_os = "android", target_os = "ios"), not(target_family = "wasm"), not(target_env = "sgx")))'.dependencies.ureq]
workspace = true
features = ["native-tls"]

[target.'cfg(all(not(any(target_os = "android", target_os = "ios")), not(target_family = "wasm"), not(target_env = "sgx")))'.dependencies.ureq]
workspace = true
features = ["rustls"]

[dev-dependencies.snarkvm-algorithms]
path = "../algorithms"
default-features = false

[dev-dependencies.snarkvm-circuit]
path = "../circuit"

[dev-dependencies.snarkvm-console]
path = "../console"

[dev-dependencies.snarkvm-ledger-block]
path = "../ledger/block"

[dev-dependencies.snarkvm-ledger-store]
path = "../ledger/store"

[dev-dependencies.snarkvm-synthesizer]
path = "../synthesizer"

[dev-dependencies.wasm-bindgen-test]
version = "0.3.37"

[dev-dependencies.hex]
workspace = true

[dev-dependencies.rand]
workspace = true

[package.metadata.cargo-machete]
ignored = [
  "js-sys", # needed for wasm feature
]
