[package]
name = "snarkvm-synthesizer-error"
version = "4.10.0"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "A decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/ProvableHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [
  "compilers",
  "cryptography",
  "mathematics",
  "wasm",
  "web-programming"
]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "Apache-2.0"
edition = "2024"
rust-version = "1.96.0" # Attention - Change the MSRV in rust-toolchain and in .circleci/config.yml as well

[dependencies.snarkvm-circuit-environment]
workspace = true

[dependencies.snarkvm-console-network]
workspace = true

[dependencies.snarkvm-console-program]
workspace = true

[dependencies.anyhow]
workspace = true

[dependencies.thiserror]
workspace = true
