[package]
name = "snarkvm-circuit-types-boolean"
version = "4.10.0"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Boolean circuit for a decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/ProvableHQ/snarkVM"
license = "Apache-2.0"
edition = "2024"

[[bench]]
name = "and"
path = "benches/and.rs"
harness = false

[dependencies.snarkvm-console-types-boolean]
workspace = true

[dependencies.snarkvm-circuit-environment]
workspace = true

[dev-dependencies.criterion]
workspace = true
